
-- SELECIONANDO TABELA ONDE QUERO PRODUTOS DIFERENTE DE "P"
  SELECT * FROM produto where `TIPO` != "P";

-- SELECIONANDO UNIDADE E AS CONTANDO 
  SELECT COUNT(*) FROM produto where UNIDADE = 'UN';

-- SELECIONANDO A TABELA DE PRODUTOS
 SELECT * FROM produto;

 -- UMA SELEÇAO DISTINTA 
 SELECT DISTINCT UNIDADE FROM produto where TIPO = 'S';

-- SELECIONANDO PRODUTOS COM TIPO "S"
SELECT * FROM produto where TIPO = 'S';

-- SELECIONANDO PRODUTO QUE TEM A MINÍMA QUANTIDADE DO TIPO "S"
 SELECT MIN(QUANTIDADE),DESCRICAO FROM produto where TIPO = 'S';
